name: Njdemicco
favicon: null
layout_spectrum: 0.3428938891738653
typography_spectrum: 0.6268589922692627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4582929699681699
  lightness: 0.3703627334907651
  saturation: 0.7403306406922638
  rhythmicContrast: 0.07894299528561532
purpose: []
